libro/books/urls.py
from django.urls import path
from .import views

app_name = 'books'
urlpatterns = [
    path('', views.homepage, name='home'),
    path('browse/', views.browse, name='browse'),
    path('explore/',views.explore, name='explore'),
    path('about/', views.about, name='about'),
]

libro/libro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
]  + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

libro/books/models.py
from django.db import models
import datetime

# Create your models here.
class list(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100, default='Unknown')
    image = models.ImageField(upload_to='images/', default='images/default.jpg')
    body = models.TextField()
    uploaded_at = models.DateTimeField(default=datetime.datetime.now)

    def __str__(self):
        return self.title
    
class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=150)
    message = models.TextField()

    def __str__(self):
        return self.name

libro/books/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'message']

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'placeholder': 'Name'})
        self.fields['email'].widget.attrs.update({'placeholder': 'Email'})
        self.fields['message'].widget.attrs.update({'placeholder': 'Message'})

libro/books/views.py
from django.shortcuts import render,redirect
from .models import list
from .forms import ContactForm


def homepage(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('books:home')
    else:
        form = ContactForm()
    return render(request, 'index.html', {'form': form})

def browse(request):
    return render(request, 'browse.html')

def explore(request):
    booklist = list.objects.all()
    return render(request, 'explore.html', {'lists': booklist})

def about(request):
    return render(request, 'about.html')

libro/books/templates/about.html
{% load static %}
<html>
	<head>
		<title>Django Website</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'css/main.css' %}" />
		<link rel="stylesheet" href="{% static 'css/fontawesome-all.min.css' %}">
		<noscript><link rel="stylesheet" href="{% static 'css/noscript.css' %}" /></noscript>
	</head>
	<body class="is-preload">
		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
					<header id="header">
						<div class="inner">

							<!-- Logo -->
								<a href="#" class="logo">
									<span class="symbol"><img src="{% static 'css/images/bkk.png' %}" alt="" /></span><span class="title">Libro</span>
								</a>

							<!-- Nav -->
								<nav>
									<ul>
										<li><a href="#menu">Menu</a></li>
									</ul>
								</nav>

						</div>
					</header>

				<!-- Menu -->
					<nav id="menu">
						<h2>Menu</h2>
						<ul>
							<li><a href="{% url 'books:home' %}">Home</a></li>
							<li><a href="{%url 'books:browse' %}">Browse</a></li>
							<li><a href="{%url 'books:explore' %}">Explore</a></li>
							<li><a href="{%url 'books:about' %}">About</a></li>
						</ul>
					</nav>

                    <!-- Main -->
					<div id="main">
						<div class="inner">
							<h1>About Us</h1>
							<p>About Us

                                Welcome to LIBRO, your premier destination for discovering and enjoying a vast collection of eBooks across all genres and interests.
                                <br>At LIBRO, we are passionate about making reading accessible and enjoyable for everyone, whether you're a casual reader or a devoted book lover.<br>
                                
                                Our Mission: Our mission is to provide a comprehensive and user-friendly platform where readers can easily find, purchase, and download their favorite eBooks. We aim to support and promote both established authors and emerging talents, offering a diverse range of titles to suit every taste.
                                <br>
                                What We Offer: <br>
                                
                                Extensive Collection: Explore our extensive library of eBooks, including bestsellers, classics, and indie gems. From fiction and non-fiction to academic texts and self-help guides, we have something for every reader.<br>
                                Seamless Experience: Enjoy a seamless reading experience with our easy-to-navigate website and downloadable eBooks compatible with various devices.<br>
                                Personalized Recommendations: Receive personalized recommendations based on your reading preferences and interests.<br>
                                Our Commitment: At [eBook Site Name], we are committed to providing exceptional customer service and ensuring a safe, secure, and enjoyable reading experience. We value our community of readers and strive to continually enhance our offerings to meet your needs.
                                <hr>
                                Thank you for choosing LIBRO Happy reading!</p>
						</div>
					</div>

                    <footer>
						<p class"copyright">&copy; Untitled Design:Codeephile</p>
					</footer>

        
    			</div>

                <!-- Scripts -->
                <script src="{% static 'js/jquery.min.js' %}"></script>
                <script src="{% static 'js/browser.min.js' %}"></script>
                <script src="{% static 'js/breakpoints.min.js' %}"></script>
                <script src="{% static 'js/util.js' %}"></script>
                <script src="{% static 'js/main.js' %}"></script>
        
            </body>
        </html>

libro/books/templates/browse.html
{% load static %}
<html>
	<head>
		<title>Django Website</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'css/main.css' %}" />
		<link rel="stylesheet" href="{% static 'css/fontawesome-all.min.css' %}">
		<noscript><link rel="stylesheet" href="{% static 'css/noscript.css' %}" /></noscript>
	</head>
	<body class="is-preload">
		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
					<header id="header">
						<div class="inner">

							<!-- Logo -->
								<a href="#" class="logo">
									<span class="symbol"><img src="{% static 'css/images/bkk.png' %}" alt="" /></span><span class="title">Libro</span>
								</a>

							<!-- Nav -->
								<nav>
									<ul>
										<li><a href="#menu">Menu</a></li>
									</ul>
								</nav>

						</div>
					</header>

				<!-- Menu -->
					<nav id="menu">
						<h2>Menu</h2>
						<ul>
							<li><a href="{% url 'books:home' %}">Home</a></li>
							<li><a href="{%url 'books:browse' %}">Browse</a></li>
							<li><a href="{%url 'books:explore' %}">Explore</a></li>
							<li><a href="{%url 'books:about' %}">About</a></li>
						</ul>
					</nav>

				<!-- Main -->
					<div id="main">
						<div class="inner">
							<h1>Browse</h1>
							<span class="image main"><img src="{% static 'css/images/blib.jpg' %}" alt="" /></span>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis dapibus rutrum facilisis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam tristique libero eu nibh porttitor fermentum. Nullam venenatis erat id vehicula viverra. Nunc ultrices eros ut ultricies condimentum. Mauris risus lacus, blandit sit amet venenatis non, bibendum vitae dolor. Nunc lorem mauris, fringilla in aliquam at, euismod in lectus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In non lorem sit amet elit placerat maximus. Pellentesque aliquam maximus risus, vel venenatis mauris vehicula hendrerit.</p>
							<p>Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque venenatis dolor imperdiet dolor mattis sagittis. Praesent rutrum sem diam, vitae egestas enim auctor sit amet. Pellentesque leo mauris, consectetur id ipsum sit amet, fersapien risus, commodo eget turpis at, elementum convallis elit. Pellentesque enim turpis, hendrerit tristique lorem ipsum dolor.</p>
							<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic ut nulla, maxime sint delectus rerum nihil, iure deserunt nam in rem perferendis incidunt id asperiores ipsam commodi. Cupiditate, repellat in.</p>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis dapibus rutrum facilisis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam tristique libero eu nibh porttitor fermentum. Nullam venenatis erat id vehicula viverra. Nunc ultrices eros ut ultricies condimentum. Mauris risus lacus, blandit sit amet venenatis non, bibendum vitae dolor. Nunc lorem mauris, fringilla in aliquam at, euismod in lectus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In non lorem sit amet elit placerat maximus. Pellentesque aliquam maximus risus, vel venenatis mauris vehicula hendrerit.</p>
							<br> <a href="{% url 'books:explore' %}">See More</a>
						</div>
					</div>
					<footer>
						<p class"copyright">&copy; Untitled Design:Codeephile</p>
					</footer>
			</div>

		<!-- Scripts -->
		<script src="{% static 'js/jquery.min.js' %}"></script>
		<script src="{% static 'js/browser.min.js' %}"></script>
		<script src="{% static 'js/breakpoints.min.js' %}"></script>
		<script src="{% static 'js/util.js' %}"></script>
		<script src="{% static 'js/main.js' %}"></script>

	</body>
</html>

libro/books/templates/explore.html
{% load static %}
<html>
	<head>
		<title>Django Website</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'css/main.css' %}" />
		<link rel="stylesheet" href="{% static 'css/fontawesome-all.min.css' %}">
		<noscript><link rel="stylesheet" href="{% static 'css/noscript.css' %}" /></noscript>
	</head>
	<body class="is-preload">
		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
					<header id="header">
						<div class="inner">

							<!-- Logo -->
								<a href="#" class="logo">
									<span class="symbol"><img src="{% static 'css/images/bkk.png' %}" alt="" /></span><span class="title">Libro</span>
								</a>

							<!-- Nav -->
								<nav>
									<ul>
										<li><a href="#menu">Menu</a></li>
									</ul>
								</nav>

						</div>
					</header>

				<!-- Menu -->
					<nav id="menu">
						<h2>Menu</h2>
						<ul>
							<li><a href="{% url 'books:home' %}">Home</a></li>
							<li><a href="{%url 'books:browse' %}">Browse</a></li>
							<li><a href="{%url 'books:explore' %}">Explore</a></li>
							<li><a href="{%url 'books:about' %}">About</a></li>
						</ul>
					</nav>

					<!--list-->
					<div class="content">
						<ul class="team">
							<h1>Authors and their Books</h1>
							{% for l in lists %}
							<li class="member">
								<div class="thumb"><img src="{{ l.image.url }}"></div>
								<div class="description">
									<h3>{{ l.title }}</h3>
									<p>{{ l.author }}</p>
									<p>{{ l.body }}</p>
									<p>{{ l.uploaded_at }}</p>
								</div>
							</li>
							{% endfor %}
						</ul>
					</div>
					<footer>
						<p class"copyright">&copy; Untitled Design:Codeephile</p>
					</footer>

				
			</div>

		<!-- Scripts -->
		<script src="{% static 'js/jquery.min.js' %}"></script>
		<script src="{% static 'js/browser.min.js' %}"></script>
		<script src="{% static 'js/breakpoints.min.js' %}"></script>
		<script src="{% static 'js/util.js' %}"></script>
		<script src="{% static 'js/main.js' %}"></script>

	</body>
</html>

libro/books/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    homepage 
{% endblock %}

{% block body %}

    <!-- Main -->
    <div id="main">
        <div class="inner">
            <header>
                <h1>Welcome from Libro, a free ebook reading site<br /></h1>
                 <p>Dive into a world of captivating stories and expert insights with our diverse collection of ebooks. From thrilling novels and heartfelt romances to transformative self-help and cutting-edge non-fiction, we have something for every reader. Whether you’re a bookworm or a casual reader, explore our library and find your next page-turner today!

                    <br>Happy Reading!</p>
            </header>
            
            <section class="tiles">
                <article class="style1">
                    <span class="image">
                        <img src="{% static 'css/images/hpbook.jpg' %}" alt="" />
                    </span>
                    <a href="{% url 'books:browse' %}">
                        <h2>Adventure</h2>
                        <div class="content">
                            <p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
                        </div>
                    </a>
                </article>
                <article class="style2">
                    <span class="image">
                        <img src="{% static 'css/images/harry.jpg' %}" alt="" />
                    </span>
                    <a href="{% url 'books:browse' %}">
                        <h2>Fiction</h2>
                        <div class="content">
                            <p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
                        </div>
                    </a>
                </article>
                <article class="style3">
                    <span class="image">
                        <img src="{% static 'css/images/lotr.jpg' %}" alt="" />
                    </span>
                    <a href="{% url 'books:browse' %}">
                        <h2>Movie</h2>
                        <div class="content">
                            <p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
                        </div>
                    </a>
                </article>
                <article class="style4">
                    <span class="image">
                        <img src="{% static 'css/images/wshpe.jpg' %}" alt="" />
                    </span>
                    <a href="{% url 'books:browse' %}">
                        <h2>Story</h2>
                        <div class="content">
                            <p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
                        </div>
                    </a>
                </article>
                <article class="style5">
                    <span class="image">
                        <img src="{% static 'css/images/got.jpg' %}" alt="" />
                    </span>
                    <a href="{% url 'books:browse' %}">
                        <h2>Game</h2>
                        <div class="content">
                            <p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
                        </div>
                    </a>
                </article>
                <article class="style6">
                    <span class="image">
                        <img src="{% static 'css/images/histori.jpg' %}" alt="" />
                    </span>
                    <a href="{% url 'books:browse' %}">
                        <h2>History</h2>
                        <div class="content">
                            <p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
                        </div>
                    </a>
                </article> 

                <article class="style1">
                    <span class="image">
                        <img src="{% static 'css/images/hpbook.jpg' %}" alt="" />
                    </span>
                    <a href="{% url 'books:browse' %}">
                        <h2>Adventure</h2>
                        <div class="content">
                            <p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
                        </div>
                    </a>
                </article>
                <article class="style2">
                    <span class="image">
                        <img src="{% static 'css/images/harry.jpg' %}" alt="" />
                    </span>
                    <a href="{% url 'books:browse' %}">
                        <h2>Fiction</h2>
                        <div class="content">
                            <p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
                        </div>
                    </a>
                </article>
                <article class="style3">
                    <span class="image">
                        <img src="{% static 'css/images/lotr.jpg' %}" alt="" />
                    </span>
                    <a href="{% url 'books:browse' %}">
                        <h2>Movie</h2>
                        <div class="content">
                            <p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
                        </div>
                    </a>
                </article>
                <article class="style4">
                    <span class="image">
                        <img src="{% static 'css/images/wshpe.jpg' %}" alt="" />
                    </span>
                    <a href="{% url 'books:browse' %}">
                        <h2>Story</h2>
                        <div class="content">
                            <p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
                        </div>
                    </a>
                </article>
                <article class="style5">
                    <span class="image">
                        <img src="{% static 'css/images/got.jpg' %}" alt="" />
                    </span>
                    <a href="{% url 'books:browse' %}">
                        <h2>Game</h2>
                        <div class="content">
                            <p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
                        </div>
                    </a>
                </article>
                <article class="style6">
                    <span class="image">
                        <img src="{% static 'css/images/histori.jpg' %}" alt="" />
                    </span>
                    <a href="{% url 'books:browse' %}">
                        <h2>History</h2>
                        <div class="content">
                            <p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
                        </div>
                    </a>
                </article> 
            </section>
        </div>
    </div>

    			<!--footer form-->
                <footer id="footer">
                    <div class="inner">
                        <section>
                            <h2>Get in touch</h2>
                            <form method="post" action="{% url 'books:home' %}">
                                {% csrf_token %}
                                <div class="fields">
                                    <div class="field half">
                                        {{ form.name }}
                                    </div>
                                    <div class="field half">
                                        {{ form.email }}
                                    </div>
                                    <div class="field">
                                        {{ form.message }}
                                    </div>
                                </div>
                                <ul class="actions">
                                    <li><input type="submit" value="Send" class="primary" />
                                    </li>
                                </ul>
                            </form>
                        </section>
                        <section>
                            <h2>Follow</h2>
                            <ul class="icons">
                                <li><a href="#" class="icon brands style2 fa-twitter"><span class="label">Twitter</span></a></li>
                                <li><a href="#" class="icon brands style2 fa-facebook-f"><span class="label">Facebook</span></a></li>
                                <li><a href="#" class="icon brands style2 fa-instagram"><span class="label">Instagram</span></a></li>
                                <li><a href="#" class="icon brands style2 fa-dribbble"><span class="label">Dribbble</span></a></li>
                                <li><a href="#" class="icon brands style2 fa-github"><span class="label">GitHub</span></a></li>
                                <li><a href="#" class="icon brands style2 fa-500px"><span class="label">500px</span></a></li>
                                <li><a href="#" class="icon solid style2 fa-phone"><span class="label">Phone</span></a></li>
                                <li><a href="#" class="icon solid style2 fa-envelope"><span class="label">Email</span></a></li>
                            </ul>
                        </section>
                    </div>
                </footer>


{% endblock %}

libro/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--links-->

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" 
    crossorigin="anonymous">

    <title>Django Website</title>
    <!--custom css link-->
    
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontawesome-all.min.css' %}">
    <noscript><link rel="stylesheet" href="{% static 'css/noscript.css' %}"></noscript>
   
</head>
<body class="is-preload">
    <!--wrapper body-->
    <div id="wrapper">
    {% include 'header.html' %}

    {% block body %} {% endblock %}

    {% include 'footer.html' %}

    </div>

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/browser.min.js' %}"></script>
    <script src="{% static 'js/breakpoints.min.js' %}"></script>
    <script src="{% static 'js/util.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    
</body>
</html>

libro/templates/footer.html
<footer>
    <p class"copyright">&copy; Untitled Design:Codeephile</p>
</footer>

libro/templates/header.html
{% load static %}

<header id="header">
    <div class="inner">

        <!-- Logo -->
            <a href="#" class="logo">
                <span class="symbol"><img src="{% static "css/images/bkk.png" %}" alt="" /></span><span class="title">Libro</span>
            </a>

        <!-- Nav -->
            <nav>
                <ul>
                    <li><a href="#menu">Menu</a></li>
                </ul>
            </nav>

    </div>
</header>

				<!-- Menu -->
                <nav id="menu">
                    <h2>Menu</h2>
                    <ul>
                        <li><a href="{% url 'books:home' %}">Home</a></li>
                        <li><a href="{% url 'books:browse' %}">Browse</a></li>
                        <li><a href="{% url 'books:explore' %}">Explore</a></li>
                        <li><a href="{% url 'books:about' %}">About</a></li>
                    </ul>
                </nav>